version: '3'
services:
  web:
    image: ruby:2.7
    command: bash -c "bundle install && rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ./storage:/myapp/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
  db:
    image: nouchka/sqlite3
    volumes:
      - ./db:/root/db
    command: sqlite3 /root/db/development.sqlite3
