version: '3.8'

services:
  rails_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/rails_app
      - bundle_cache:/usr/local/bundle
    environment:
      RAILS_ENV: production

volumes:
  bundle_cache:
